appConfig:
  COSMOS_ENDPOINT: ""
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/xxx/xxx/xxx
  FETCH_INTERVAL: 15s
  CHAIN_ID: ""

replicaCount: 1

image:
  repository: ghcr.io/composablefi/cosmos-notifier
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
