---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmos-notifier.fullname" . }}
  labels:
    {{- include "cosmos-notifier.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.appConfig }}
  {{ $key }}: {{ $value | quote }} 
  {{ end }}