replicaCount: 1

image:
  repository: composablefi/composable-ibc
  pullPolicy: IfNotPresent
  tag: "master"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

args:
  - relay
  - --config-a
  - /config-a.toml
  - --config-b
  - /config-b.toml
  - --config-core
  - /config-core.toml

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
