
# -- Provide a name in place of node for `app:` labels
nameOverride: ""

# -- Provide a name to substitute for the full names of resources
fullnameOverride: ""

# -- Additional common labels on pods and services
extraLabels: {}


# -- Number of replicas
replicaCount: 1

# -- Image of relayer.
image:
  # -- Image repository
  repository: composablefi/composable-ibc

  # -- Image pull policy
  pullPolicy: IfNotPresent

  # -- Image tag
  tag: "master"

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

args:
  - relay
  - --config-a
  - /opt/hyperspace/config-a.toml
  - --config-b
  - /opt/hyperspace/config-b.toml
  - --config-core
  - /opt/hyperspace/config-core/config-core.toml

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# -- Relayers config
config:
  # -- Prometheus metrics
  prometheus_endpoint: "0.0.0.0:19617"