apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "indexer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "indexer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.appConfig.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- if .Values.appSecret.enabled }}
            {{- range $key, $value := .Values.appSecret.env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value }}
                  key: {{ $key | lower }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
